# Generated by Django 3.1.7 on 2021-03-04 16:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Worker', max_length=250, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Список задач',
                'verbose_name_plural': 'Список задач',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('created', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('due_on', models.DateField(verbose_name='Дедлайн')),
                ('owner', models.CharField(blank=True, default='admin', max_length=250, verbose_name='Владелец')),
                ('mark', models.BooleanField(default=False, verbose_name='Статус')),
                ('task_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='main.tasklist', verbose_name='Задачи')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['mark', 'created', '-due_on'],
            },
        ),
    ]
