# Generated by Django 3.1.7 on 2021-03-19 15:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('created', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Created at')),
                ('due_on', models.DateField(default=django.utils.timezone.now, verbose_name='Deadline')),
                ('owner', models.CharField(blank=True, max_length=250, verbose_name='Owner')),
                ('mark', models.BooleanField(default=False, verbose_name='Status')),
                ('task_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='main.todolist', verbose_name='TodoList')),
            ],
            options={
                'verbose_name': 'Todo',
                'verbose_name_plural': 'Todos',
            },
        ),
    ]
